/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "message": {
        "HELLO": string;
        "INTERNAL_SERVER_ERROR": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
